on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
     - cron: '*/30 * * * *'


jobs:
# considering we have earlier jobs that needs does the deployment, we develop a Devops strategy that runs all the jobs in sequence, we can hav the job placed as the last step where we can run our automated test just after the deployment.
  test_run:
    name: rest assured mvn test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Tests
        run: mvn test
